Improvements for event data
scandipwa/gtm-graphql pull request #4
Opened 2020-10-07 07:22 UTC by denissdubinin

- Add missing data for various events
- Add event for 404 page

2020-10-12 06:34 UTC, denissdubinin commented on src/scandipwa/app/component/GoogleTagManager/events/NotFound.event.js
> +            eventAction: window.location.href,
withRouter is not working in this case

2020-10-20 08:25 UTC, yeegor requested changes
Overall code quality is very good
Only minor changes are requested. Thank you!

2020-10-20 08:25 UTC, yeegor commented on src/scandipwa/app/component/GoogleTagManager/events/Purchase.event.js
> +            coupon_discount_amount: +roundPrice(discount_amount || 0)
Consider setting the default values for these variables during the restructuring. Just as you did with the `coupon_code`. Or are the other things different?
E.g. 
```js
getActionFields(orderId = '', {
    tax_amount = 0, 
    grand_total = 0, 
    shipping_amount = 0, 
    discount_amount = 0, 
    coupon_code = ''
}) { ... }
```

2020-10-20 08:25 UTC, yeegor commented on src/scandipwa/app/component/GoogleTagManager/utils/Product.js
> +     */
I doubt that this function returns a number.

2020-10-20 08:25 UTC, yeegor commented on src/scandipwa/app/component/GoogleTagManager/utils/Product.js
> +                    final_price: {
Are you 100% sure these changes are not project-specific? It seems they might be.

2020-10-20 08:25 UTC, yeegor commented on src/scandipwa/app/plugin/StoreModifications.plugin.js
> +            const CUSTOMER = 'customer';
Consider importing this from somewhere

2020-10-20 08:25 UTC, yeegor commented on src/scandipwa/app/plugin/query/ConfigQuery.plugin.js
> +export class ConfigQueryPlugin extends PureComponent {
You should not extend PureComponent with the plugin classes.
Also, FYI, I see that you actually don't need a plugin class here at all. We are shifting towards removing the classes from .plugin.js files when they don't serve some specific purpose, e.g. preserving the state.

2023-11-21 09:54 UTC, closed without merging